import type { GameId } from './types';
import { MAX_PLAYERS, MIN_PLAYERS } from './types';

/**
 * Catálogo dos minijogos. É a única fonte de verdade para nomes, textos, cores
 * e regras exibidas no portal — adicionar um jogo novo é adicionar uma entrada
 * aqui + um módulo em `games/`.
 */

export interface GameTheme {
  from: string;
  to: string;
  accent: string;
  ink: string;
  /** cor do piso da arena */
  arena: string;
  arenaEdge: string;
  /** cor do fundo fora da arena */
  backdrop: string;
  backdropDeep: string;
}

export interface GameCatalogEntry {
  id: GameId;
  name: string;
  tagline: string;
  pitch: string;
  description: string;
  objective: string;
  minPlayers: number;
  maxPlayers: number;
  avgSeconds: number;
  durationLabel: string;
  /**
   * Como o HUD e a tela de resultado devem ler o placar deste jogo. Deixar isso
   * no catálogo evita um `switch (gameId)` espalhado pela interface a cada jogo
   * novo que entra no portal.
   */
  scoreKind: 'survive' | 'time' | 'percent' | 'points';
  /** vidas iniciais; 1 significa eliminação no primeiro erro */
  lives: number;
  chaos: 1 | 2 | 3 | 4 | 5;
  difficulty: string;
  howTo: string[];
  tips: string[];
  hudHint: string;
  tags: string[];
  theme: GameTheme;
}

export const GAME_CATALOG: GameCatalogEntry[] = [
  {
    id: 'push',
    name: 'PUSH!',
    tagline: 'Empurra, voa, ri.',
    pitch: 'Arena encolhendo, dash pesado e ninguém a salvo.',
    description:
      'Todo mundo entra na mesma plataforma flutuante. Use o dash para trombar nos amigos e mandar todos para fora enquanto o chão vai desaparecendo por baixo dos seus pés.',
    objective: 'Seja o último de pé na arena.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 65,
    durationLabel: '45 – 95s',
    scoreKind: 'survive',
    lives: 1,
    chaos: 5,
    difficulty: 'Fácil de entender',
    howTo: [
      'Mova com WASD, setas ou o direcional na tela.',
      'Dash com Espaço, clique ou o botão redondo.',
      'Cada trombada acumulada te deixa mais leve — e mais fácil de arremessar.',
      'A arena encolhe até virar um pontinho. Não fique na beirada.',
    ],
    tips: [
      'Dash tem recarga: guarde para o contra-ataque.',
      'Deixe os outros brigarem e chegue por trás.',
      'No gelo você desliza — freie antes da borda.',
    ],
    hudHint: 'Sobreviventes restantes',
    tags: ['Sobrevivência', 'Empurrão', 'Caos'],
    theme: {
      from: '#6C41F5',
      to: '#3FC6FF',
      accent: '#FFC93C',
      ink: '#231155',
      arena: '#EFE7FF',
      arenaEdge: '#A98BFF',
      backdrop: '#4B23B8',
      backdropDeep: '#2B1173',
    },
  },
  {
    id: 'crown',
    name: 'CROWN!',
    tagline: 'A coroa queima na cabeça.',
    pitch: 'Segure a coroa o máximo que puder. Todo mundo quer roubar.',
    description:
      'Uma coroa dourada aparece no meio da arena. Quem toca nela vira o alvo de todos: o cronômetro pessoal sobe enquanto a coroa estiver na sua cabeça, mas um toque dos outros já leva o brilho embora.',
    objective: 'Acumule tempo de coroa até bater a meta.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '50 – 90s',
    scoreKind: 'time',
    lives: 1,
    chaos: 4,
    difficulty: 'Fácil de entender',
    howTo: [
      'Toque na coroa para pegá-la.',
      'Com a coroa você fica um tico mais lento — e no centro das atenções.',
      'Encoste no portador para roubar. Existe um breve instante de imunidade.',
      'Uma trombada forte derruba a coroa no chão: corrida livre.',
    ],
    tips: [
      'Use o dash para fugir em curva, não em linha reta.',
      'Sem coroa você corre mais rápido: aproveite para cercar.',
      'Perto da meta o ritmo acelera. Segure firme.',
    ],
    hudHint: 'Tempo de coroa por jogador',
    tags: ['Perseguição', 'Roubo', 'Tensão'],
    theme: {
      from: '#FFC93C',
      to: '#FF7A59',
      accent: '#6C41F5',
      ink: '#6B3D00',
      arena: '#FFF3D6',
      arenaEdge: '#F5AE10',
      backdrop: '#C4610F',
      backdropDeep: '#8A3D06',
    },
  },
  {
    id: 'bomb',
    name: 'BOMB!',
    tagline: 'Passa. Passa. PASSA!',
    pitch: 'A bomba está com você. O pavio é curto e mentiroso.',
    description:
      'Um jogador começa com a bomba e precisa encostar em alguém para repassar antes do estouro. O pavio varia a cada rodada, então nunca dá para confiar na contagem.',
    objective: 'Não esteja com a bomba quando ela explodir.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 45,
    durationLabel: '30 – 60s',
    scoreKind: 'survive',
    lives: 2,
    chaos: 5,
    difficulty: 'Fácil de entender',
    howTo: [
      'Quem tem a bomba brilha e vibra — corra atrás de alguém.',
      'Encostar em outro jogador passa a bomba na hora.',
      'Depois de passar existe um cooldown: não dá para devolver na cara.',
      'A explosão elimina só quem estiver segurando.',
    ],
    tips: [
      'Dash é ótimo para alcançar quem está fugindo.',
      'Sem bomba, mantenha distância e circule pela borda.',
      'Com poucos jogadores a arena aperta: não tem para onde correr.',
    ],
    hudHint: 'Pavio da bomba e quem está com ela',
    tags: ['Pega-pega', 'Tensão', 'Explosão'],
    theme: {
      from: '#FF7A59',
      to: '#F5348A',
      accent: '#FFC93C',
      ink: '#7A0E42',
      arena: '#FFEDE6',
      arenaEdge: '#FF9B7A',
      backdrop: '#B81E4F',
      backdropDeep: '#7C0F34',
    },
  },
  {
    id: 'paint',
    name: 'PAINT!',
    tagline: 'O chão é seu. Por enquanto.',
    pitch: 'Pinte o mapa correndo e cubra a tinta dos outros.',
    description:
      'Cada jogador tem uma cor e pinta o chão por onde passa. Pintar por cima do adversário vale dobrado no visual e no placar. Nos últimos segundos entra o final rush e tudo pinta mais grosso.',
    objective: 'Domine a maior porcentagem do mapa.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 75,
    durationLabel: '75s cravados',
    scoreKind: 'percent',
    lives: 1,
    chaos: 3,
    difficulty: 'Fácil de entender',
    howTo: [
      'Ande para pintar. Simples assim.',
      'O dash deixa um rastro largo e cobre mais rápido.',
      'Pintar por cima do inimigo rouba o território dele.',
      'Nos 10 segundos finais o pincel engrossa: viradas acontecem.',
    ],
    tips: [
      'Cantos ficam esquecidos e valem muita porcentagem.',
      'Roubar o miolo do inimigo dói mais que pintar área vazia.',
      'Não pare de andar. Parado você não pinta.',
    ],
    hudHint: 'Porcentagem de cada cor',
    tags: ['Território', 'Corrida', 'Satisfação'],
    theme: {
      from: '#2BD9A8',
      to: '#3FC6FF',
      accent: '#FF5CA3',
      ink: '#0A5741',
      arena: '#F2FFFB',
      arenaEdge: '#7FE7CB',
      backdrop: '#0E9B8A',
      backdropDeep: '#08655C',
    },
  },
  {
    id: 'dont-fall',
    name: "DON'T FALL!",
    tagline: 'O chão está te traindo.',
    pitch: 'Cada passo quebra um bloco. Sobra espaço para um.',
    description:
      'O piso é feito de blocos que racham quando você pisa e caem pouco depois. Aos poucos o mapa vira um arquipélago de plataformas e o dash passa a ser a única ponte.',
    objective: 'Seja o último a não cair.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 55,
    durationLabel: '35 – 75s',
    scoreKind: 'survive',
    lives: 1,
    chaos: 4,
    difficulty: 'Fácil de entender',
    howTo: [
      'Pisou, rachou. Rachou, caiu.',
      'Use o dash para atravessar buracos.',
      'Blocos piscam antes de sumir: leia o aviso.',
      'Empurrar alguém para o vazio também conta.',
    ],
    tips: [
      'Ande em círculos largos para gastar menos chão.',
      'Guarde uma ilha de blocos intactos como plano B.',
      'No mano a mano a câmera aproxima. Respire.',
    ],
    hudHint: 'Jogadores restantes',
    tags: ['Plataforma', 'Timing', 'Sobrevivência'],
    theme: {
      from: '#FF5CA3',
      to: '#8F66FF',
      accent: '#2BD9A8',
      ink: '#4B1050',
      arena: '#FFF0FA',
      arenaEdge: '#FF9BC6',
      backdrop: '#7A2C9B',
      backdropDeep: '#4A1566',
    },
  },
];

// ---------------------------------------------------------------------------
// Segunda leva de minijogos
// ---------------------------------------------------------------------------

const MORE_GAMES: GameCatalogEntry[] = [
  {
    id: 'coleta',
    name: 'COLETA!',
    tagline: 'Corre que a estrela é minha.',
    pitch: 'Estrelas caem no mapa. Pegue mais que os outros em 70 segundos.',
    description:
      'Estrelas aparecem sem parar e cada uma vale um ponto. De vez em quando surge uma dourada valendo três. Não tem eliminação: é corrida pura, roubo de estrela na cara e trombada para atrapalhar quem chegou primeiro.',
    objective: 'Some mais pontos que todo mundo.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '70s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 3,
    difficulty: 'Entende na hora',
    howTo: [
      'Encoste na estrela para pegar.',
      'Dourada vale 3 — todo mundo vai querer.',
      'Dash é atalho: use para chegar antes.',
      'Trombar no adversário faz ele perder a corrida.',
    ],
    tips: [
      'Fique no meio do mapa: as estrelas nascem em qualquer lugar.',
      'Deixe o amigo chegar primeiro e roube a próxima.',
      'Guarde o dash para as douradas.',
    ],
    hudHint: 'Pontos de cada jogador',
    tags: ['Corrida', 'Coleta', 'Sem eliminação'],
    theme: {
      from: '#FFC93C',
      to: '#2BD9A8',
      accent: '#6C41F5',
      ink: '#6B3D00',
      arena: '#FFFBEA',
      arenaEdge: '#F5AE10',
      backdrop: '#1EA68C',
      backdropDeep: '#12705F',
    },
  },
  {
    id: 'zona',
    name: 'ZONA!',
    tagline: 'O lugar mais disputado do mapa.',
    pitch: 'Fique dentro do círculo. Sozinho. Boa sorte.',
    description:
      'Um círculo marca a zona e quem estiver lá dentro ganha ponto por segundo. O detalhe cruel: se tiver mais de um jogador na zona, ninguém pontua. Ou você empurra todo mundo para fora, ou não sai do zero. A zona muda de lugar a cada poucos segundos.',
    objective: 'Domine a zona sozinho até bater a meta.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '40 – 95s',
    scoreKind: 'time',
    lives: 1,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Dentro do círculo você pontua.',
      'Com dois ou mais lá dentro, ninguém pontua.',
      'Use o dash para expulsar quem chegou junto.',
      'A zona se move — corra para a próxima antes dos outros.',
    ],
    tips: [
      'Chegar primeiro vale menos que chegar sozinho.',
      'Espere na borda e empurre quem está pontuando.',
      'Quando a zona for anunciada, saia na frente.',
    ],
    hudHint: 'Pontos e quem está dominando',
    tags: ['Território', 'Empurrão', 'Disputa'],
    theme: {
      from: '#6C41F5',
      to: '#FF5CA3',
      accent: '#FFC93C',
      ink: '#2B1466',
      arena: '#F4EEFF',
      arenaEdge: '#A98BFF',
      backdrop: '#5B2BC9',
      backdropDeep: '#35157F',
    },
  },
  {
    id: 'parede',
    name: 'PAREDE!',
    tagline: 'Acha o buraco. Rápido.',
    pitch: 'Paredes atravessam a arena. Só tem uma passagem.',
    description:
      'Paredes varrem o cenário de um lado ao outro, cada uma com uma única passagem. Ler onde está o buraco e chegar nele antes da parede é tudo. Errou? Perde uma vida e a próxima já está vindo — mais rápida.',
    objective: 'Sobreviva às paredes até sobrar você.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 50,
    durationLabel: '40 – 65s',
    scoreKind: 'survive',
    lives: 3,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'A passagem é o único lugar seguro.',
      'Bateu na parede, perde uma vida.',
      'As paredes ficam mais rápidas com o tempo.',
      'Dash ajuda a corrigir na última hora.',
    ],
    tips: [
      'Olhe a próxima parede enquanto passa pela atual.',
      'O centro costuma ser o caminho mais curto.',
      'Não fique colado na borda: passagem lá é rara.',
    ],
    hudHint: 'Vidas restantes de cada um',
    tags: ['Reflexo', 'Leitura', 'Sobrevivência'],
    theme: {
      from: '#3FC6FF',
      to: '#6C41F5',
      accent: '#FFC93C',
      ink: '#0A4767',
      arena: '#EAF8FF',
      arenaEdge: '#77D6FF',
      backdrop: '#1C63C7',
      backdropDeep: '#13337F',
    },
  },
  {
    id: 'gol',
    name: 'GOL!',
    tagline: 'A bola é sua inimiga.',
    pitch: 'Empurre a bola para o gol dos outros e proteja o seu.',
    description:
      'Uma bola no meio e um gol para cada jogador na borda da arena. Empurrar a bola para o gol de alguém tira uma vida dessa pessoa e marca ponto para você. Defender e atacar ao mesmo tempo, sem time, sem juiz.',
    objective: 'Sobre vivo depois de furar o gol dos outros.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '30 – 100s',
    scoreKind: 'points',
    lives: 4,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Encoste na bola para empurrar; dash chuta forte.',
      'Bola no seu gol = você perde uma vida.',
      'Quem tocou por último leva o ponto.',
      'Seu gol é o da sua cor.',
    ],
    tips: [
      'Ficar em cima do gol é defesa, mas você não pontua.',
      'Rebote na parede é gol também.',
      'Deixe dois adversários se atrapalharem e chute depois.',
    ],
    hudHint: 'Gols marcados e vidas de cada gol',
    tags: ['Bola', 'Defesa', 'Caos'],
    theme: {
      from: '#2BD9A8',
      to: '#149FE0',
      accent: '#FFC93C',
      ink: '#0A5741',
      arena: '#EFFFF9',
      arenaEdge: '#6FEDC8',
      backdrop: '#0C8F8C',
      backdropDeep: '#075C63',
    },
  },
  {
    id: 'corrida',
    name: 'CORRIDA!',
    tagline: 'Primeiro no anel leva.',
    pitch: 'Um alvo por vez. Quem toca primeiro pontua.',
    description:
      'Um anel luminoso aparece em algum canto da arena e quem tocar primeiro marca ponto. Na hora que alguém marca, o próximo anel nasce longe. É sprint atrás de sprint, com trombada liberada para tirar o amigo do caminho.',
    objective: 'Seja o primeiro a marcar 8 pontos.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 35,
    durationLabel: '20 – 45s',
    scoreKind: 'points',
    lives: 1,
    chaos: 3,
    difficulty: 'Entende na hora',
    howTo: [
      'Toque no anel antes dos outros.',
      'Cada anel vale 1 ponto.',
      'Dash é sua arma de velocidade.',
      'Empurrar quem está na frente é parte do jogo.',
    ],
    tips: [
      'Corte caminho pelo centro em vez de seguir a borda.',
      'Guarde o dash para a reta final do anel.',
      'Se não vai chegar, atrapalhe quem vai.',
    ],
    hudHint: 'Pontos e meta da corrida',
    tags: ['Velocidade', 'Sprint', 'Disputa'],
    theme: {
      from: '#FF7A59',
      to: '#FFC93C',
      accent: '#6C41F5',
      ink: '#7A2A18',
      arena: '#FFF4E8',
      arenaEdge: '#FFA98D',
      backdrop: '#D1582A',
      backdropDeep: '#8E3416',
    },
  },
  {
    id: 'cores',
    name: 'CORES!',
    tagline: 'Pise na cor. Ou tchau.',
    pitch: 'O chão tem seis cores. Uma é chamada. Corre.',
    description:
      'A arena é dividida em seis blocos coloridos. Uma cor é anunciada e um cronômetro curto começa: quando ele zera, quem não estiver na cor certa perde uma vida. Depois as cores embaralham e o tempo diminui.',
    objective: 'Esteja sempre na cor chamada.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '50 – 88s',
    scoreKind: 'survive',
    lives: 3,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'A cor chamada aparece grande no topo.',
      'Esteja em cima dela quando o tempo zerar.',
      'As cores trocam de lugar a cada rodada.',
      'O tempo vai encurtando.',
    ],
    tips: [
      'Fique perto do meio: dá para alcançar mais cores.',
      'Empurrar alguém para fora da cor é maldade permitida.',
      'Decore onde cada cor ficou antes de a próxima ser chamada.',
    ],
    hudHint: 'Cor chamada, tempo e vidas',
    tags: ['Reflexo', 'Festa', 'Trollagem'],
    theme: {
      from: '#FF5CA3',
      to: '#3FC6FF',
      accent: '#FFC93C',
      ink: '#4B1050',
      arena: '#FFF6FB',
      arenaEdge: '#FF9BC6',
      backdrop: '#8E2BA8',
      backdropDeep: '#4F1568',
    },
  },
  {
    id: 'raio',
    name: 'RAIO!',
    tagline: 'Dança entre os feixes.',
    pitch: 'Feixes giram pela arena. Ache o vão e fique nele.',
    description:
      'Feixes de luz giram a partir do centro, e a cada avanço da partida entra um feixe novo, mais rápido. O jogo é ler a rotação, escolher o vão certo e se mexer no ritmo — encostar custa uma vida.',
    objective: 'Sobreviva aos feixes mais que todos.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 45,
    durationLabel: '30 – 80s',
    scoreKind: 'survive',
    lives: 3,
    chaos: 3,
    difficulty: 'Entende na hora',
    howTo: [
      'Feixe aceso machuca; feixe piscando vai acender.',
      'Ande no sentido da rotação para ganhar tempo.',
      'Cada vida perdida dá um instante de invencibilidade.',
      'Dash atravessa o vão apertado.',
    ],
    tips: [
      'Perto do centro os feixes passam mais rápido.',
      'Escolha um vão e acompanhe, não fique trocando.',
      'Empurrar alguém para o feixe conta como jogada.',
    ],
    hudHint: 'Vidas e feixes ativos',
    tags: ['Esquiva', 'Ritmo', 'Sobrevivência'],
    theme: {
      from: '#8F66FF',
      to: '#FF5CA3',
      accent: '#3FC6FF',
      ink: '#2B1466',
      arena: '#F2ECFF',
      arenaEdge: '#B79BFF',
      backdrop: '#33176E',
      backdropDeep: '#1B0B44',
    },
  },
  {
    id: 'mina',
    name: 'MINA!',
    tagline: 'Ganância tem preço.',
    pitch: 'Cada bloco novo vale ponto. Alguns explodem.',
    description:
      'O chão é um tabuleiro de blocos fechados. Pisar em um bloco novo revela: seguro vale ponto e fica da sua cor, mina explode e custa uma vida. Quanto mais você avança, mais pontos — e mais chance de achar o que não queria.',
    objective: 'Revele mais blocos seguros que os outros.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 38,
    durationLabel: '20 – 60s',
    scoreKind: 'points',
    lives: 3,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Pise em blocos fechados para revelar.',
      'Seguro = 1 ponto e vira sua cor.',
      'Mina = explosão, uma vida e empurrão em todo mundo por perto.',
      'Blocos já revelados não valem nada.',
    ],
    tips: [
      'Bloco vizinho de área limpa costuma ser mais seguro.',
      'Deixe o afoito abrir caminho e colete atrás.',
      'Explosão empurra: use isso a seu favor.',
    ],
    hudHint: 'Pontos, vidas e blocos restantes',
    tags: ['Risco', 'Tabuleiro', 'Tensão'],
    theme: {
      from: '#F5AE10',
      to: '#EE5533',
      accent: '#2BD9A8',
      ink: '#6B3D00',
      arena: '#FFF3DF',
      arenaEdge: '#FFC93C',
      backdrop: '#B5561A',
      backdropDeep: '#71300C',
    },
  },
  {
    id: 'rastro',
    name: 'RASTRO!',
    tagline: 'O caminho vira parede.',
    pitch: 'Você deixa rastro. E o rastro machuca — inclusive o seu.',
    description:
      'Cada jogador vai deixando um rastro luminoso que endurece um instante depois de passar. Encostar em qualquer rastro, seu ou dos outros, custa uma vida. Os rastros somem com o tempo, então a arena está sempre se reabrindo.',
    objective: 'Sobreviva aos rastros mais que os outros.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 35,
    durationLabel: '25 – 50s',
    scoreKind: 'survive',
    lives: 4,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Seu rastro endurece pouco depois de você passar.',
      'Encostar em rastro custa uma vida.',
      'Rastros desaparecem depois de alguns segundos.',
      'Dash atravessa rápido, mas deixa rastro mais grosso.',
    ],
    tips: [
      'Curvas largas te dão saída; curvas fechadas te enterram.',
      'Fechar o adversário numa espiral é a jogada da casa.',
      'Não corra atrás de quem está fugindo pelo próprio rastro.',
    ],
    hudHint: 'Vidas restantes de cada um',
    tags: ['Rastro', 'Armadilha', 'Sobrevivência'],
    theme: {
      from: '#3FC6FF',
      to: '#2BD9A8',
      accent: '#FF5CA3',
      ink: '#0A4767',
      arena: '#EAFFFB',
      arenaEdge: '#7FF0CF',
      backdrop: '#0E5F8C',
      backdropDeep: '#062F52',
    },
  },
  {
    id: 'meteoro',
    name: 'METEORO!',
    tagline: 'Olha pra cima. Ou pro chão.',
    pitch: 'Sombras marcam onde vai cair. Saia de lá.',
    description:
      'Meteoros caem sem parar e cada um avisa antes: uma sombra cresce no chão marcando o ponto de impacto. Acertar em cima custa uma vida, e a onda de choque empurra quem estava por perto — direto para o próximo impacto, se você tiver azar.',
    objective: 'Escape dos meteoros até sobrar você.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '45 – 90s',
    scoreKind: 'survive',
    lives: 3,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Sombra crescendo no chão = impacto vindo.',
      'Sair do círculo antes da hora é o jogo todo.',
      'A onda de choque empurra mesmo sem acertar.',
      'Com o tempo caem mais meteoros ao mesmo tempo.',
    ],
    tips: [
      'Não pare de andar: sombra nova pode nascer em cima de você.',
      'Use a onda de choque para empurrar quem está distraído.',
      'Canto da arena tem menos saída. Fique no miolo.',
    ],
    hudHint: 'Vidas e meteoros a caminho',
    tags: ['Esquiva', 'Pressão', 'Sobrevivência'],
    theme: {
      from: '#FF7A59',
      to: '#8F66FF',
      accent: '#FFC93C',
      ink: '#4B1050',
      arena: '#FFEFE9',
      arenaEdge: '#FFA98D',
      backdrop: '#5C2A7A',
      backdropDeep: '#2C1046',
    },
  },
];

// ---------------------------------------------------------------------------
// Terceira leva
// ---------------------------------------------------------------------------

const EVEN_MORE_GAMES: GameCatalogEntry[] = [
  {
    id: 'sombra',
    name: 'SOMBRA!',
    tagline: 'Quem é pego vira caçador.',
    pitch: 'Começa um atrás de todos. Termina todos atrás de um.',
    description:
      'Um jogador começa como caçador. Quem for pego entra no time dele, e a arena vai virando uma matilha correndo atrás dos últimos fugitivos. Ninguém sai da partida — você só troca de lado, e o pânico aumenta a cada captura.',
    objective: 'Fique livre o máximo de tempo que conseguir.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '70s cravados',
    scoreKind: 'time',
    lives: 1,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Caçador tem aura escura e é um tico mais LENTO: ele precisa encurralar.',
      'Encostou em você? Agora você também é caçador.',
      'Fugitivo pontua a cada segundo livre.',
      'Pegou todo mundo? Começa outra caçada, e quem está liderando vira o caçador.',
    ],
    tips: [
      'Fugir para o canto é o jeito mais rápido de ser pego.',
      'Com muitos caçadores, corra pelo meio e force eles a se atrapalharem.',
      'Recém-capturado tem um instante de carência: aproveite para sumir.',
      'Liderar tem preço: a próxima caçada começa com você atrás de todos.',
    ],
    hudHint: 'Quantos fugitivos ainda restam',
    tags: ['Pega-pega', 'Infecção', 'Correria'],
    theme: {
      from: '#8F66FF',
      to: '#3A1670',
      accent: '#FFC93C',
      ink: '#1B1035',
      arena: '#EFE7FF',
      arenaEdge: '#8F66FF',
      backdrop: '#2B1466',
      backdropDeep: '#120829',
    },
  },
  {
    id: 'buraco',
    name: 'BURACO!',
    tagline: 'A física é o inimigo.',
    pitch: 'Um buraco puxa todo mundo. Sempre mais forte.',
    description:
      'Não tem o que atacar aqui: um buraco passeia pela arena sugando todos, e a força só aumenta com o tempo. Dash é a sua escapatória, e empurrar o amigo na direção do centro é a jogada mais suja do portal.',
    objective: 'Seja o último a não ser engolido.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 50,
    durationLabel: '30 – 80s',
    scoreKind: 'survive',
    lives: 1,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'A atração cresce sem parar — no fim ninguém fica parado.',
      'Dash rompe a sucção por um instante.',
      'Encostar em alguém joga essa pessoa para dentro.',
      'O buraco anda devagar pela arena: fique de olho.',
    ],
    tips: [
      'Corra em círculo em volta do buraco, não em linha reta para longe.',
      'Parede não é abrigo: você fica sem espaço para manobrar.',
      'Guarde o dash para quando a sucção já estiver te levando.',
    ],
    hudHint: 'Sobreviventes restantes',
    tags: ['Física', 'Sobrevivência', 'Empurrão'],
    theme: {
      from: '#8F66FF',
      to: '#1B1035',
      accent: '#3FC6FF',
      ink: '#150B32',
      arena: '#EDE6FF',
      arenaEdge: '#6C41F5',
      backdrop: '#231152',
      backdropDeep: '#0B0420',
    },
  },
  {
    id: 'peso',
    name: 'PESO!',
    tagline: 'Tanque ou foguete. Escolha.',
    pitch: 'Cada haltere te deixa mais lento e mais perigoso.',
    description:
      'Halteres caem na arena. Cada um que você pega tira velocidade, mas te deixa mais difícil de empurrar e transforma a sua trombada em arremesso. Leve você foge de todos; pesado você manda todos para fora — se conseguir alcançar alguém.',
    objective: 'Seja o último na arena.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '40 – 80s',
    scoreKind: 'survive',
    lives: 1,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Encoste no haltere para carregar (até 5).',
      'Mais peso = mais lento, mais resistente e mais forte na trombada.',
      'Quem é leve vai longe quando toma pancada de um pesado.',
      'Sair da arena elimina. No fim do tempo, entre sobreviventes ganha quem carrega mais.',
    ],
    tips: [
      'Não pegue peso perto da borda: você fica sem velocidade para voltar.',
      'Contra um pesado, ataque em movimento e nunca de frente.',
      'Dois halteres já mudam o jogo. Cinco te tornam um prédio.',
    ],
    hudHint: 'Sobreviventes e carga de cada um',
    tags: ['Sumô', 'Escolha', 'Empurrão'],
    theme: {
      from: '#FFC93C',
      to: '#EE5533',
      accent: '#6C41F5',
      ink: '#6B3D00',
      arena: '#FFF6E6',
      arenaEdge: '#F5AE10',
      backdrop: '#A8501B',
      backdropDeep: '#5E2A0C',
    },
  },
  {
    id: 'ladrao',
    name: 'LADRÃO!',
    tagline: 'Moeda na mão não vale nada.',
    pitch: 'Junte moedas, deposite no cofre — e cuidado com quem encostar.',
    description:
      'Moedas aparecem no chão, mas elas só valem ponto depois de depositadas no cofre. Quem encostar em você leva tudo o que está na sua mão. Cada segundo é uma decisão: volta agora para garantir ou arrisca uma moeda a mais.',
    objective: 'Deposite mais moedas que todo mundo.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 80,
    durationLabel: '80s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Encoste nas moedas para carregar.',
      'Entre no cofre para transformar a carga em pontos.',
      'Tocar em alguém rouba TODA a carga da pessoa.',
      'O cofre muda de lugar de vez em quando.',
    ],
    tips: [
      'Carregar muito é convite: deposite antes de virar alvo.',
      'Espere o ganancioso encher a mão e roube na porta do cofre.',
      'Depois de um roubo, os dois ficam um instante imunes.',
    ],
    hudHint: 'Moedas depositadas por jogador',
    tags: ['Roubo', 'Risco', 'Correria'],
    theme: {
      from: '#2BD9A8',
      to: '#FFC93C',
      accent: '#FF5CA3',
      ink: '#0A5741',
      arena: '#F4FFF6',
      arenaEdge: '#6FEDC8',
      backdrop: '#0E7F62',
      backdropDeep: '#05402F',
    },
  },
  {
    id: 'cadeiras',
    name: 'CADEIRAS!',
    tagline: 'A música parou.',
    pitch: 'Sempre falta uma cadeira. E elas giram.',
    description:
      'Dança das cadeiras com o clássico problema: tem sempre uma cadeira menos que gente. Enquanto a música toca, as cadeiras giram pela arena; no apito elas congelam e quem não estiver em cima de uma está fora. A cada rodada sai outra cadeira.',
    objective: 'Garanta uma cadeira em cada apito.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 45,
    durationLabel: '25 – 70s',
    scoreKind: 'points',
    lives: 2,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Com a música tocando, as cadeiras giram.',
      'No apito elas param — esteja em cima de uma.',
      'Quem chegou mais ao centro da cadeira fica com ela.',
      'Ficar de fora tira uma vida, não elimina na hora (sala pequena tem vida extra).',
    ],
    tips: [
      'Não cole na cadeira cedo: ela vai girar para longe.',
      'Empurrar alguém para fora da cadeira no apito é legal aqui.',
      'Fique entre duas cadeiras para ter plano B.',
    ],
    hudHint: 'Cadeiras restantes e tempo da música',
    tags: ['Festa', 'Reflexo', 'Trollagem'],
    theme: {
      from: '#FF5CA3',
      to: '#FFC93C',
      accent: '#6C41F5',
      ink: '#7A0E42',
      arena: '#FFF4FA',
      arenaEdge: '#FF9BC6',
      backdrop: '#C41E66',
      backdropDeep: '#7A0E42',
    },
  },
];

// ---------------------------------------------------------------------------
// Quarta leva
// ---------------------------------------------------------------------------

const PARTY_GAMES: GameCatalogEntry[] = [
  {
    id: 'onda',
    name: 'ONDA!',
    tagline: 'Sai da água.',
    pitch: 'A onda avisa antes. Isso não vai te salvar.',
    description:
      'A água varre a arena de um lado ao outro e as pedras são o único lugar seco. No começo cabe todo mundo na mesma pedra; algumas ondas depois não cabe mais ninguém, e a última mão que sobra é a que empurra.',
    objective: 'Esteja em cima de uma pedra quando a onda passar.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 48,
    durationLabel: '25 – 80s',
    scoreKind: 'survive',
    lives: 3,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'O aviso mostra de que lado a onda vem.',
      'Pedra é lugar seco: qualquer parte dela serve.',
      'Ser pego fora da pedra custa uma vida (sala pequena ganha uma extra).',
      'As pedras mudam de lugar e encolhem a cada onda.',
    ],
    tips: [
      'Escolha a pedra pelo espaço que sobra, não pela distância.',
      'Dash no último instante entra na pedra; dash cedo te deixa sem fuga.',
      'Empurrar alguém para fora da pedra é totalmente permitido.',
    ],
    hudHint: 'Vidas de cada jogador e a onda a caminho',
    tags: ['Reflexo', 'Territorial', 'Empurrão'],
    theme: {
      from: '#3FC6FF',
      to: '#1B4B9E',
      accent: '#FFE38C',
      ink: '#0B2B5E',
      arena: '#EAF6FF',
      arenaEdge: '#5AA9FF',
      backdrop: '#123C7E',
      backdropDeep: '#061C3F',
    },
  },
  {
    id: 'semaforo',
    name: 'SEMÁFORO!',
    tagline: 'Verde, amarelo, estátua.',
    pitch: 'No amarelo você tem que andar devagar. Boa sorte.',
    description:
      'Corrida em linha reta com um sinal mandando em você: no verde corre, no vermelho é estátua e no amarelo tem que andar devagar — nem parar, nem correr. Quem desobedece volta um bom pedaço do caminho.',
    objective: 'Cruze a linha de chegada mais vezes que todo mundo.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '70s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Verde: corre o quanto quiser.',
      'Amarelo: tem que estar se movendo, mas devagar.',
      'Vermelho: parado. Dash conta como movimento.',
      'Cruzou a linha? Ponto — e você volta para a largada.',
    ],
    tips: [
      'No vermelho, solte tudo: velocidade sobrando ainda é multa.',
      'Trombar em alguém no vermelho faz a pessoa se mover. Pense nisso.',
      'O verde encurta com o tempo: não guarde o avanço para depois.',
    ],
    hudHint: 'Sinal atual e linhas cruzadas por jogador',
    tags: ['Reflexo', 'Corrida', 'Trollagem'],
    theme: {
      from: '#2BD9A8',
      to: '#0E7F62',
      accent: '#FF4D5E',
      ink: '#08432F',
      arena: '#F1FFF8',
      arenaEdge: '#59E2BB',
      backdrop: '#0C6B52',
      backdropDeep: '#043226',
    },
  },
  {
    id: 'carimbo',
    name: 'CARIMBO!',
    tagline: 'Na ordem certa.',
    pitch: 'Seis carimbos, uma ordem, todo mundo correndo junto.',
    description:
      'A ordem aparece na tela: triângulo, coração, raio. Pise nos carimbos nessa sequência para marcar ponto. Como a ordem é a mesma para todos, os seis carimbos viram seis engarrafamentos — e pisar no carimbo errado te manda para o começo.',
    objective: 'Complete mais sequências que os outros.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 75,
    durationLabel: '75s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 5,
    difficulty: 'Pega o jeito rápido',
    howTo: [
      'A sequência de três símbolos vale para todos ao mesmo tempo.',
      'Pise nos carimbos na ordem mostrada.',
      'Carimbo errado no meio da sequência volta você ao começo.',
      'Quem completa muda a ordem e embaralha os símbolos.',
    ],
    tips: [
      'Planeje a rota inteira antes de sair: atravessar em cima do errado custa.',
      'Empurrar alguém para o carimbo errado zera a sequência da pessoa.',
      'Quando alguém está no último passo, atrapalhe em vez de correr.',
    ],
    hudHint: 'A ordem chamada e o seu passo atual',
    tags: ['Memória', 'Correria', 'Trollagem'],
    theme: {
      from: '#FFC93C',
      to: '#FF5CA3',
      accent: '#6C41F5',
      ink: '#7A3B00',
      arena: '#FFF8EC',
      arenaEdge: '#FFB43C',
      backdrop: '#C4562B',
      backdropDeep: '#6B2410',
    },
  },
  {
    id: 'trem',
    name: 'TREM!',
    tagline: 'Cada um no seu vagão.',
    pitch: 'O trem tem a sua cor em algum vagão. Ache antes do apito.',
    description:
      'A cada apito o trem precisa estar montado: uma fila de vagões, cada um com a cor de um jogador. Ache o seu, chegue lá e segure a posição — e se o vagão do lado também acertar, os dois ganham dobrado.',
    objective: 'Esteja no seu vagão quando o apito tocar.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 78,
    durationLabel: '78s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Cada vagão tem a cor do jogador que precisa estar nele.',
      'O trilho muda de lugar e de sentido a cada rodada.',
      'Vagão certo vale 1 ponto. Colado em outro vagão certo, vale 2.',
      'A ordem é sorteada de novo toda rodada.',
    ],
    tips: [
      'Olhe a cor, não a posição: o trem inverte o sentido sem avisar.',
      'Ajudar o vizinho a acertar vale ponto para você também.',
      'No fim do tempo da rodada, tirar alguém do vagão vale mais que correr.',
    ],
    hudHint: 'Tempo até o apito e vagões certos',
    tags: ['Festa', 'Aliança', 'Reflexo'],
    theme: {
      from: '#8F66FF',
      to: '#2BD9A8',
      accent: '#FFC93C',
      ink: '#25145C',
      arena: '#F3EEFF',
      arenaEdge: '#9B7BFF',
      backdrop: '#372089',
      backdropDeep: '#160A3D',
    },
  },
  {
    id: 'gangorra',
    name: 'GANGORRA!',
    tagline: 'O chão decide.',
    pitch: 'A arena inclina para o lado onde tem mais gente.',
    description:
      'A arena é uma prancha apoiada no meio. Ela pende para o lado mais pesado, todo mundo escorrega ladeira abaixo e caixotes caem do céu para bagunçar a conta. Aqui ninguém empurra ninguém: quem empurra é o próprio chão.',
    objective: 'Seja o último em pé na prancha.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 55,
    durationLabel: '30 – 80s',
    scoreKind: 'survive',
    lives: 1,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Seu peso conta: quanto mais longe do centro, mais você inclina.',
      'O lado baixo escorrega, e o escorregão aumenta com o tempo.',
      'Caixote pesa mais que gente — e pode ser empurrado.',
      'Saiu pela laterais, acabou.',
    ],
    tips: [
      'Ficar no centro é seguro e inútil: o balanço cresce e você vai ter que escolher um lado.',
      'Empurrar um caixote para o lado alto derruba a arena inteira.',
      'Dash subindo a ladeira é o único jeito de voltar do lado baixo.',
    ],
    hudHint: 'Sobreviventes e para que lado a prancha pende',
    tags: ['Física', 'Sobrevivência', 'Equilíbrio'],
    theme: {
      from: '#FF7A59',
      to: '#8F66FF',
      accent: '#3FC6FF',
      ink: '#5E2410',
      arena: '#FFF1E8',
      arenaEdge: '#FF9E7A',
      backdrop: '#8A3A6B',
      backdropDeep: '#3D1330',
    },
  },
];

// ---------------------------------------------------------------------------
// Quinta leva
// ---------------------------------------------------------------------------

const LAST_GAMES: GameCatalogEntry[] = [
  {
    id: 'bolha',
    name: 'BOLHA!',
    tagline: 'Parado é que enche.',
    pitch: 'Sua bolha só cresce se você ficar quieto. Boa sorte com isso.',
    description:
      'A sua bolha enche enquanto você fica parado e, cheia, estoura valendo ponto. O problema é o caminho até lá: bolha grande deixa você lento, e qualquer um que te encostar fura a sua bolha e leva metade do ar para a dele.',
    objective: 'Estoure mais bolhas cheias que todo mundo.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '70s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 4,
    difficulty: 'Entende na hora',
    howTo: [
      'Fique parado para encher a bolha.',
      'Bolha cheia estoura sozinha e vale ponto.',
      'Encostar em alguém fura a bolha da pessoa e você leva metade.',
      'Quanto maior a sua bolha, mais devagar você anda.',
    ],
    tips: [
      'Encher longe de todos é seguro e lento. Encher no meio é rápido e suicida.',
      'Se estão vindo, esvazie andando um pouco: perde ar, não perde tudo.',
      'Deixe o ganancioso quase encher antes de furar.',
    ],
    hudHint: 'O quanto a bolha de cada um está cheia',
    tags: ['Risco', 'Paciência', 'Trollagem'],
    theme: {
      from: '#3FC6FF',
      to: '#8F66FF',
      accent: '#FFE38C',
      ink: '#123C7E',
      arena: '#F0FAFF',
      arenaEdge: '#7CD4FF',
      backdrop: '#2A4EA8',
      backdropDeep: '#0F1E4F',
    },
  },
  {
    id: 'ima',
    name: 'ÍMÃ!',
    tagline: 'Igual repele. Diferente atrai.',
    pitch: 'A polaridade muda no meio da briga.',
    description:
      'Todos viram ímãs em cima de uma plataforma redonda. Polo igual se repele, polo diferente se atrai — e a polaridade de todo mundo é sorteada de novo a cada poucos segundos, com aviso. Quando troca, quem estava colado voa e quem estava fugindo é puxado de volta.',
    objective: 'Seja o último na plataforma.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 70,
    durationLabel: '40 – 75s',
    scoreKind: 'survive',
    lives: 1,
    chaos: 5,
    difficulty: 'Pega o jeito rápido',
    howTo: [
      'O sinal em cima de cada um mostra o polo.',
      'Polo igual empurra, polo diferente puxa. Quanto mais perto, mais forte.',
      'O aviso aparece um segundo antes da troca.',
      'Saiu da plataforma, acabou.',
    ],
    tips: [
      'Fique entre dois que se repelem: eles trabalham para você.',
      'Antes da troca, imagine onde você vai ser jogado.',
      'Dash vence o campo por um instante. Só um instante.',
    ],
    hudHint: 'Sobreviventes e a polaridade de cada um',
    tags: ['Física', 'Sumô', 'Caos'],
    theme: {
      from: '#FF5CA3',
      to: '#3FC6FF',
      accent: '#FFC93C',
      ink: '#2B1054',
      arena: '#F6F0FF',
      arenaEdge: '#B58CFF',
      backdrop: '#4B1C7A',
      backdropDeep: '#1A0838',
    },
  },
  {
    id: 'espelho',
    name: 'ESPELHO!',
    tagline: 'Você joga com dois.',
    pitch: 'Seu reflexo também pega estrela. E também empurra.',
    description:
      'Uma linha de espelho corta a arena e você controla dois corpos ao mesmo tempo: você e o seu reflexo. Os dois pegam estrela, os dois empurram gente. E o espelho desliza devagar, então o seu reflexo se mexe mesmo quando você está parado.',
    objective: 'Pegue mais estrelas que todo mundo, com qualquer um dos seus corpos.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 68,
    durationLabel: '68s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 4,
    difficulty: 'Pega o jeito rápido',
    howTo: [
      'Seu reflexo fica do outro lado da linha, na posição espelhada.',
      'Estrela vale igual, pega quem chegar — corpo ou reflexo.',
      'O reflexo empurra os outros jogadores de verdade.',
      'A linha do espelho desliza de um lado para o outro.',
    ],
    tips: [
      'Para o reflexo ir para a direita, você vai para a esquerda.',
      'Estrela colada no espelho é a mais fácil: os dois corpos chegam junto.',
      'Dá para atacar alguém com o reflexo enquanto você foge com o corpo.',
    ],
    hudHint: 'Estrelas de cada jogador',
    tags: ['Cabeça', 'Coleta', 'Original'],
    theme: {
      from: '#2BD9A8',
      to: '#8F66FF',
      accent: '#FFFFFF',
      ink: '#123C5E',
      arena: '#EEFBFF',
      arenaEdge: '#8FE3F5',
      backdrop: '#1D5F86',
      backdropDeep: '#0A2540',
    },
  },
  {
    id: 'dois',
    name: 'DOIS!',
    tagline: 'Grupos de dois. Ou de três.',
    pitch: 'O número é chamado. Alguém vai sobrar.',
    description:
      'O número aparece e todo mundo tem que se juntar em grupos exatamente desse tamanho antes do tempo acabar. Grupo com gente sobrando não vale, grupo incompleto não vale — e quando o número é 1, é o contrário: você precisa estar sozinho.',
    objective: 'Esteja sempre no grupo do tamanho certo.',
    // com dois jogadores não existe "sobrar alguém": o jogo só faz sentido a três
    minPlayers: 3,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 55,
    durationLabel: '30 – 80s',
    scoreKind: 'survive',
    lives: 3,
    chaos: 5,
    difficulty: 'Entende na hora',
    howTo: [
      'Colado em alguém conta como estar no mesmo grupo.',
      'O anel em volta de você mostra o tamanho do seu grupo agora.',
      'Anel verde é grupo certo. Vermelho não vale nada.',
      'Ficar de fora custa uma vida. Você tem três.',
    ],
    tips: [
      'Não espere o tempo acabar para decidir com quem você vai.',
      'Empurrar o intruso é mais rápido que procurar outro grupo.',
      'No "SOZINHO!" o centro da arena é uma armadilha.',
    ],
    hudHint: 'Número chamado e vidas de cada um',
    tags: ['Festa', 'Social', 'Reflexo'],
    theme: {
      from: '#FFC93C',
      to: '#2BD9A8',
      accent: '#FF5CA3',
      ink: '#6B4A00',
      arena: '#FFFDF0',
      arenaEdge: '#FFD96B',
      backdrop: '#B58A15',
      backdropDeep: '#5E4405',
    },
  },
  {
    id: 'caca',
    name: 'CAÇA!',
    tagline: 'Tá quente. Tá quente!',
    pitch: 'O baú está enterrado. Seu único aparelho é a temperatura.',
    description:
      'Um baú está escondido em algum lugar da arena e ninguém sabe onde. O que você tem é um medidor: quanto mais perto, mais quente. Dash cava. E como o calor dos outros também aparece na tela, quando alguém esquenta a correria começa.',
    objective: 'Desenterre mais baús que todo mundo.',
    minPlayers: MIN_PLAYERS,
    maxPlayers: MAX_PLAYERS,
    avgSeconds: 75,
    durationLabel: '75s cravados',
    scoreKind: 'points',
    lives: 1,
    chaos: 3,
    difficulty: 'Entende na hora',
    howTo: [
      'O anel em volta de você é o medidor: azul é frio, vermelho é fervendo.',
      'Dash cava no lugar onde você está.',
      'Cavou certo: ponto, e um baú novo é enterrado em outro canto.',
      'O medidor dos outros jogadores também é visível.',
    ],
    tips: [
      'Ande em linha reta para saber se está esquentando ou esfriando.',
      'Cavar custa o dash: sem dash você não foge de ninguém.',
      'Seguir quem está vermelho é feio, mas funciona.',
    ],
    hudHint: 'Temperatura de cada jogador e baús encontrados',
    tags: ['Investigação', 'Social', 'Coleta'],
    theme: {
      from: '#FF7A59',
      to: '#FFC93C',
      accent: '#3FC6FF',
      ink: '#6B2410',
      arena: '#FFF4E4',
      arenaEdge: '#FFB273',
      backdrop: '#A34A1C',
      backdropDeep: '#4D1C07',
    },
  },
];

GAME_CATALOG.push(...MORE_GAMES, ...EVEN_MORE_GAMES, ...PARTY_GAMES, ...LAST_GAMES);

export const GAME_IDS: GameId[] = GAME_CATALOG.map((g) => g.id);

export function getGameMeta(id: GameId | string | undefined): GameCatalogEntry {
  return GAME_CATALOG.find((g) => g.id === id) ?? GAME_CATALOG[0];
}

export function isGameId(value: unknown): value is GameId {
  return typeof value === 'string' && GAME_IDS.includes(value as GameId);
}
